const image = document.getElementById('cover'); 
const title = document.getElementById('music-title');
const artist = document.getElementById('music-artist'); const currentTimeEl = document.getElementById('current-time'); 
const durationEl = document.getElementById('duration'); 
const progress = document.getElementById('progress'); 
const playerProgress = document.getElementById('player-progress'); 
const prevBtn = document.getElementById('prev'); 
const playBtn = document.getElementById('play'); 
const nextBtn = document.getElementById('next'); 
const background = document.getElementById('bg-img');